#!/usr/bin/env node
/**
 * Launch readiness check.
 *
 * The page is finished; the facts on it are not. Everything below is something
 * a visitor can see, or something that silently does nothing, and every one of
 * them is a single edit in lib/site.ts or lib/content.ts.
 *
 * Run it before any deploy:   npm run preflight
 * Exits non-zero on blockers, so it can gate a build.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => { try { return readFileSync(join(root, p), 'utf8'); } catch { return ''; } };

const site = read('lib/site.ts');
const content = read('lib/content.ts');
const env = { ...process.env };

const checks = [];
const add = (severity, area, problem, fix) => checks.push({ severity, area, problem, fix });

// Sample rows carry `placeholder: true`. Counting them is how this knows the
// difference between "not built yet" and "built, still fake".
const countIn = (arrayName, typeName) => {
  const start = content.indexOf(`export const ${arrayName}: ${typeName}`);
  if (start === -1) return { total: 0, sample: 0 };
  const slice = content.slice(start, content.indexOf('\n];', start));
  return { total: (slice.match(/\{/g) || []).length, sample: (slice.match(/placeholder: true/g) || []).length };
};

// ── Things a visitor can see ────────────────────────────────────────────────
if (!env.NEXT_PUBLIC_WHATSAPP && /whatsapp: env\.whatsapp \|\| '919000000000'/.test(site)) {
  add('blocker', 'Phone', 'The WhatsApp number is still 919000000000. It is live on every CTA and inside the Course JSON-LD.',
      'Set NEXT_PUBLIC_WHATSAPP, or change SITE.whatsapp in lib/site.ts.');
}
if (!env.NEXT_PUBLIC_PHONE_DISPLAY && /\+91 90000 00000/.test(site)) {
  add('blocker', 'Phone', 'The displayed number reads "+91 90000 00000" in the footer and the final CTA.',
      'Set NEXT_PUBLIC_PHONE_DISPLAY, or change SITE.phoneDisplay.');
}
if (/streetAddress: 'RS Puram, Coimbatore'/.test(site)) {
  add('blocker', 'Address', 'The address has no building or street. It also feeds LocalBusiness JSON-LD, so it has to match your Google Business Profile exactly.',
      'Set SITE.streetAddress, SITE.postalCode and SITE.geo to the real location.');
}
if (/lat: 11\.0168, lng: 76\.9558/.test(site)) {
  add('warning', 'Address', 'Map coordinates are the Coimbatore city centre default, not your building.',
      'Right-click your location in Google Maps, copy the coordinates into SITE.geo.');
}

// ── Trust ───────────────────────────────────────────────────────────────────
const teachers = countIn('TEACHERS', 'Teacher[]');
if (teachers.total === 0) {
  add('blocker', 'Trust', 'Nobody is named as a teacher. The page twice promises "a straight answer from someone who teaches the course" without saying who.',
      'Add one entry to TEACHERS in lib/content.ts and the section renders itself.');
} else if (teachers.sample > 0) {
  add('blocker', 'Trust', `${teachers.sample} of the ${teachers.total} teachers are sample entries reading "replace me", and the section is showing a "sample content" badge.`,
      'Put in real names, real roles, and credentials a parent could check on a phone call. Then drop the `placeholder` flag.');
}
const work = countIn('WORK', 'WorkItem[]');
if (work.total === 0) {
  add('blocker', 'Student work', 'The gallery is empty, so it does not render. The whole design direction rests on it: the page sells the course by showing what students make.',
      'Put real student work in public/work/ and list it in WORK.');
} else if (work.sample > 0) {
  add('blocker', 'Student work', `${work.sample} of the ${work.total} gallery items are still placeholder tiles, and the section is showing a "sample content" badge.`,
      'Replace the files in public/work/ with real student work and drop `placeholder: true` from each row in WORK. Nothing here can be stock or generated by anyone but a student.');
}

const testimonials = countIn('TESTIMONIALS', 'Testimonial[]');
if (testimonials.total === 0) {
  add('warning', 'Trust', 'No social proof anywhere. Every landing-page pattern for a course puts it before the price.',
      'Add real quotes to TESTIMONIALS. A parent who paid is worth three student quotes.');
} else if (testimonials.sample > 0) {
  add('blocker', 'Trust', `${testimonials.sample} of the ${testimonials.total} testimonials are sample text. A fabricated quote on a page a parent reads is the worst failure this site has available to it.`,
      'Replace with verbatim quotes from real students and drop the `placeholder` flag.');
}

// ── Things that silently do nothing ─────────────────────────────────────────
if (!env.NEXT_PUBLIC_GTM_ID) {
  add('warning', 'Analytics', 'No GTM container, so GA4 and the Meta Pixel never load and none of the conversion events are recorded.',
      'Set NEXT_PUBLIC_GTM_ID. Without it you cannot tell which ad produced an enquiry.');
}
if (!env.CALLBACK_WEBHOOK_URL) {
  add('blocker', 'Leads', 'CALLBACK_WEBHOOK_URL is unset, so the callback form refuses every submission with a 503.',
      'Point it at a Zapier/Make hook, an n8n flow, or the CRM inbound endpoint.');
}

// ── Freshness ───────────────────────────────────────────────────────────────
const iso = site.match(/batchStartISO: '(\d{4}-\d{2}-\d{2})'/)?.[1];
if (iso) {
  const start = new Date(`${iso}T00:00:00Z`);
  const days = Math.round((start - new Date()) / 86400000);
  if (days < 0) {
    add('blocker', 'Batch', `The advertised batch start (${iso}) is ${Math.abs(days)} days in the past. It shows in the hero, the final CTA and the Course schema.`,
        'Move SITE.batchStartISO to the next batch.');
  } else if (days < 7) {
    add('warning', 'Batch', `The batch starts in ${days} days. Enquiries arriving now have almost no runway.`,
        'Consider advertising the following batch.');
  }
}

// ── Report ──────────────────────────────────────────────────────────────────
const blockers = checks.filter((c) => c.severity === 'blocker');
const warnings = checks.filter((c) => c.severity === 'warning');

const bold = (s) => `\x1b[1m${s}\x1b[0m`;
const red = (s) => `\x1b[31m${s}\x1b[0m`;
const amber = (s) => `\x1b[33m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

console.log(`\n${bold('Launch readiness')}\n`);

if (checks.length === 0) {
  console.log(green('  Nothing blocking. Every placeholder has been replaced.\n'));
  process.exit(0);
}

for (const group of [
  { list: blockers, label: red('BLOCKER'), heading: 'Must fix before this page goes in front of anyone' },
  { list: warnings, label: amber('WARNING'), heading: 'Should fix' },
]) {
  if (group.list.length === 0) continue;
  console.log(`${bold(group.heading)}\n`);
  for (const c of group.list) {
    console.log(`  ${group.label}  ${bold(c.area)}`);
    console.log(`    ${c.problem}`);
    console.log(`    ${dim('Fix: ' + c.fix)}\n`);
  }
}

console.log(`${blockers.length} blocker(s), ${warnings.length} warning(s).\n`);
process.exit(blockers.length > 0 ? 1 : 0);
